name: build
on: [push, pull_request]
jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    if: >
      (( github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login ) &&
        github.event_name == 'pull_request' ) || (github.event_name == 'push' && github.event.commits != '[]' )
    env:
      GO111MODULE: on
      TARGET: amd64
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: install goberalls
        run: go get github.com/mattn/goveralls

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          exclude: "./vendor/..."

      - name: gofmt
        run: go fmt ./...

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...

      - name: Build
        run: GOARCH="${TARGET}" go build ./cmd/example

# TBD:
#      - name: Go test
#        run: sudo ./test.sh
#
#      - name: goveralls
#        uses: shogo82148/actions-goveralls@v1
#        with:
#          path-to-profile: coverage.out

